### ISSUE TITLE
SimpleTodo for code path submission

### ISSUE THREAD

**Issue by mschowdary** [mschowdary/Android#1]
Sumitted SimpleTodo app in #1 fb149f8.
@codepathreview and @codepath ,please review the submission.

**Comment by mschowdary** [comment]
Sumitted SimpleTodo app in #1 fb149f8.
@codepathreview and @codepath ,please review the submission.

**Comment by nesquena** [comment]
Thanks for submitting the Todo app. Can you please review the section in the prework about [the readme](http://courses.codepath.com/snippets/intro_to_android/prework#heading-4-submitting-the-project) for your project? In particular, check out this [README template](http://courses.codepath.com/snippets/intro_to_android/readme_templates/prework_readme.md?raw=true) and be sure to [include a GIF recorded with LiceCap](http://www.cockos.com/licecap/). Please ping me back here once that's complete.

**Comment by mschowdary** [comment]
Thanks Nathan @codepath , @codepathreview. Added read me with GIF recording 80191f7.

**Comment by nesquena** [comment]
Unfortunately the class is already full at this point, but we are happy to add you to the waitlist. For those not admitted as participants, we can also offer access to applicants as a remote observer cohort that has access to the materials and is able to work on the projects at their own pace. Let me know if you'd like to follow along as a remote observer or would rather roll over your application for May.
